title: "Technical Credit R&D"
description: "Home for Technical Credit R&D Projects"
# theme: "just-the-docs"

# If hosting on GitHub Pages, use this instead:
remote_theme: just-the-docs/just-the-docs

url: "https://technicalcredit.github.io"

nav:
  - title: "Home"
    url: /
    nav_order: 1

  - title: "Research Agenda"
    url: /research-agenda/
    nav_order: 2

  - title: "R&D Projects"
    url: /projects/
    nav_order: 3
    children:
      - title: "TC-MADR Project"
        url: /projects/tc-madr/
      - title: "TC Annotations Project"
        url: /projects/tc-annotations/
      - title: "TC Detection Project"
        url: /projects/tc-detection/


search_enabled: true
color_scheme: light

# Optional: Just-the-Docs features
aux_links:
  "GitHub Repository":
    - "https://github.com/your-username/your-repo-name"
